version: '3.8'

services:
  postgres:
    container_name: postgres-db
    image: postgres:16.2-alpine
    environment:
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # Uncomment the following line if you want to initialize the database with SQL scripts
      # - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

volumes:
  postgres_data: