import z from 'zod'
import { EncryptedDekSchema, KekSaltSchema } from '@/model/domain/auth.ts'

export const EncryptionPublicDtoSchema = z
  .object({
    kekSalt: KekSaltSchema,
    encryptedDek: EncryptedDekSchema,
  })
  .meta({
    description:
      'public data generated by the client that can only be turned into the decryption key using client private information',
  })
export type EncryptionPublicDto = z.Infer<typeof EncryptionPublicDtoSchema>
